Feature/test generation
NovaLite-doo/grupna-preksa-sept-2024 pull request #22
Opened 2024-09-18 10:53 UTC by Djoleoo

2024-09-18 11:40 UTC, MilosNesh commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/ExamController.cs
> +        try
remove try catch from the controller

2024-09-18 11:43 UTC, MilosNesh commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +    public class Query : IRequest<Response>
use command instead of query

2024-09-18 11:52 UTC, MilosNesh commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +        private readonly IRepository<Exam> _examRepository;
Are you need all repos?

2024-09-18 12:12 UTC, Djoleoo commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/ExamController.cs
> +        try
removed

2024-09-18 12:17 UTC, MilosNesh commented on Konteh/Konteh.Tests/GenerateExamTests.cs
> +            var request = new GenerateExam.Query { Email = "test@test.com", Name = "Kristina", Surname = "Zelic" };
look at lines 37-42 and choose one way to create query

2024-09-18 12:17 UTC, MilosNesh commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/ExamController.cs
> +        try
remove try catch from the controller

2024-09-18 12:17 UTC, MilosNesh commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +    public class Query : IRequest<Response>
use command instead of query

2024-09-18 12:17 UTC, MilosNesh commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +        private readonly IRepository<ExamQuestion> _examQuestionRepository;
Do you need all repos?

2024-09-18 12:17 UTC, MilosNesh commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +            var allQuestions = await _questionRepository.GetAll();
Which is the better option to call the database multiple times or to load all the data into memory?

2024-09-18 12:25 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/ExamController.cs
> +        try
lets not manually catch exceptions in controllers. Especially if all we do is log and return 500. We have an exception handler for that.

2024-09-18 12:26 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +        public List<ExamQuestion> ExamQuestions { get; set; } = [];
I don't like that we are returning domain models through our APIs, we should have proper DTOs

2024-09-18 12:26 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +            //TODO: Load info on number of questions
todo?

2024-09-18 12:26 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +            List<Question> questions = await GetQuestionsForExam(numberOfQuestionsPerCategory);
please use var instead of explicit types

2024-09-18 12:27 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +            foreach (var question in questions)
can't all of this be done in 2-3 lines of code with LINQ?

2024-09-18 12:27 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +                _examQuestionRepository.Add(examQuestion);
You don't need to add examquestions one by one if you're going add the whole exam later.

2024-09-18 12:28 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +                throw new InvalidOperationException("Candidate has already taken the test.");
In this case I think we should a ValidationException(maybe it should even be in a validator?)

2024-09-18 12:28 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Features/Exam/GenerateExam.cs
> +            var categories = Enum.GetValues(typeof(QuestionCategory)).Cast<QuestionCategory>();
var categories = Enum.GetValues<QuestionCategory>();

2024-09-18 12:30 UTC, laslorajda commented on Konteh/Konteh.Tests/GenerateExamIntegrationTests.cs
> +            //TODO dodaj u bazu nova polja
I was hoping these files for integration testing wouldn't show up in this PR, but since they are here, maybe comment a lot of it out so it doesn't cause problems.

2024-09-18 12:31 UTC, laslorajda commented on Konteh/Konteh.Tests/GenerateExamTests.cs
> +        private GenerateExam.RequestHandler? _handler;
nullable handler?!

2024-09-18 12:32 UTC, laslorajda commented on Konteh/Konteh.Tests/GenerateExamTests.cs
> +            _examRepositoryMock
I see this line repeated quite a bit

2024-09-18 12:33 UTC, laslorajda commented on Konteh/front-office-app/src/app/start-info/start-info.component.ts
> +export class StartInfoComponent {
This is an unusual name for a component, doesn't really tell me much about what it's for.

2024-09-18 12:33 UTC, laslorajda commented on Konteh/front-office-app/src/app/start-info/start-info.component.html
> +    <label for="email">Email:</label>
please use angular material UI elements

2024-09-18 12:34 UTC, laslorajda commented on Konteh/front-office-app/src/app/start-info/start-info.component.html
> +  <div *ngIf="examQuestions.length > 0">
So this component is supposed to both be for registering candidates and taking exams?
https://en.wikipedia.org/wiki/Single-responsibility_principle

2024-09-18 12:35 UTC, laslorajda commented on Konteh/front-office-app/src/app/start-info/start-info.component.ts
> +      email: ['', [Validators.required, Validators.email]],
Surprisingly the email validator in angular is actual garbage. You don't have to change it, but in real projects I recommend regex-ing it.

2024-09-18 12:35 UTC, laslorajda commented on Konteh/front-office-app/src/app/start-info/start-info.component.ts
> +      const query = GenerateExamQuery.fromJS({
const query = new GenerateExamQuery({
* init fields here *
});

2024-09-18 12:36 UTC, laslorajda requested changes
Some cleanup to do

2024-09-19 06:48 UTC, Djoleoo commented on Konteh/front-office-app/src/app/start-info/start-info.component.ts
> +      const query = GenerateExamQuery.fromJS({
didn't understand this one

2024-09-19 08:08 UTC, MilosNesh approved these changes

2024-09-19 08:09 UTC, laslorajda approved these changes

2024-09-19 08:09 UTC, merged